### ISSUE TITLE
add sleep

### ISSUE THREAD

**Issue by Obat2343** [akihikoy/fingervision#3]
https://github.com/akihikoy/fingervision/blob/d35f264530aa574d983ed76d4881f327889455ca/fingervision/src/fv_core_node.cpp#L540

  ros::Duration(0.5).sleep();

**Comment by akihikoy** [comment]
This issue has been fixed.
Actually I used Duration(0.1) instead of 0.5; of course smaller is less overhead.
Please check if it does not cause the issue.
